name: Shopify Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install playwright pandas
          playwright install --with-deps chromium
          playwright install chrome
      
      # load secrect 
      - name: Load playwright session
        run: |
          echo "${{ secrets.STATE_JSON_B64 }}" | base64 --decode > state.json

      - name: Run scraper
        run: |
          python datascrapper.py

      - name: Upload output CSV
        uses: actions/upload-artifact@v4
        with:
          name: scraping-results
          path: |
            Postcodes_*.csv
            Failedcodes_*.csv
